spring:
  application:
    name: flight-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/flight_db
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
#    hibernate:
#      ddl-auto: validate
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: drop-and-create
#              drop-target: generated/${spring.application.name}/ddl/drop-script.sql
#              create-target: generated/${spring.application.name}/ddl/create-scripts.sql

  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 0
  servlet:
    context-path: /api/flight-service
